// UserContext action types
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_LOADING = "REGISTER_USER_LOADING";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_LOADING = "LOGIN_USER_LOADING";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_LOADING = "LOGOUT_USER_LOADING";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_ERROR = "LOGOUT_USER_ERROR";

// EmployeesContext action types
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const ADD_EMPLOYEE_LOADING = "ADD_EMPLOYEE_LOADING";
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_ERROR = "ADD_EMPLOYEE_ERROR";

export const REMOVE_EMPLOYEE = "REMOVE_EMPLOYEE";
export const REMOVE_EMPLOYEE_LOADING = "REMOVE_EMPLOYEE_LOADING";
export const REMOVE_EMPLOYEE_SUCCESS = "REMOVE_EMPLOYEE_SUCCESS";
export const REMOVE_EMPLOYEE_ERROR = "REMOVE_EMPLOYEE_ERROR";

export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const UPDATE_EMPLOYEE_LOADING = "UPDATE_EMPLOYEE_LOADING";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_ERROR = "UPDATE_EMPLOYEE_ERROR";

export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const GET_EMPLOYEES_LOADING = "GET_EMPLOYEES_LOADING";
export const GET_EMPLOYEES_SUCCESS = "GET_EMPLOYEES_SUCCESS";
export const GET_EMPLOYEES_ERROR = "GET_EMPLOYEES_ERROR";

// SettingsContext action types
export const SET_THEME = "SET_THEME";
export const SET_LANGUAGE = "SET_LANGUAGE";

// LeaveContext action types
export const APPLY_FOR_LEAVE = "APPLY_FOR_LEAVE";
export const APPLY_FOR_LEAVE_LOADING = "APPLY_FOR_LEAVE_LOADING";
export const APPLY_FOR_LEAVE_SUCCESS = "APPLY_FOR_LEAVE_SUCCESS";
export const APPLY_FOR_LEAVE_ERROR = "APPLY_FOR_LEAVE_ERROR";

export const CANCEL_LEAVE = "CANCEL_LEAVE";
export const CANCEL_LEAVE_LOADING = "CANCEL_LEAVE_LOADING";
export const CANCEL_LEAVE_SUCCESS = "CANCEL_LEAVE_SUCCESS";
export const CANCEL_LEAVE_ERROR = "CANCEL_LEAVE_ERROR";

export const APPROVE_LEAVE = "APPROVE_LEAVE";
export const APPROVE_LEAVE_LOADING = "APPROVE_LEAVE_LOADING";
export const APPROVE_LEAVE_SUCCESS = "APPROVE_LEAVE_SUCCESS";
export const APPROVE_LEAVE_ERROR = "APPROVE_LEAVE_ERROR";

export const REJECT_LEAVE = "REJECT_LEAVE";
export const REJECT_LEAVE_LOADING = "REJECT_LEAVE_LOADING";
export const REJECT_LEAVE_SUCCESS = "REJECT_LEAVE_SUCCESS";
export const REJECT_LEAVE_ERROR = "REJECT_LEAVE_ERROR";

export const GET_LEAVE_HISTORY = "GET_LEAVE_HISTORY";
export const GET_LEAVE_HISTORY_LOADING = "GET_LEAVE_HISTORY_LOADING";
export const GET_LEAVE_HISTORY_SUCCESS = "GET_LEAVE_HISTORY_SUCCESS";
export const GET_LEAVE_HISTORY_ERROR = "GET_LEAVE_HISTORY_ERROR";

// PayrollContext action types
export const PROCESS_PAYROLL = "PROCESS_PAYROLL";
export const PROCESS_PAYROLL_LOADING = "PROCESS_PAYROLL_LOADING";
export const PROCESS_PAYROLL_SUCCESS = "PROCESS_PAYROLL_SUCCESS";
export const PROCESS_PAYROLL_ERROR = "PROCESS_PAYROLL_ERROR";

export const GET_PAYSLIP = "GET_PAYSLIP";
export const GET_PAYSLIP_LOADING = "GET_PAYSLIP_LOADING";
export const GET_PAYSLIP_SUCCESS = "GET_PAYSLIP_SUCCESS";
export const GET_PAYSLIP_ERROR = "GET_PAYSLIP_ERROR";

export const UPDATE_SALARY_COMPONENTS = "UPDATE_SALARY_COMPONENTS";
export const UPDATE_SALARY_COMPONENTS_LOADING =
  "UPDATE_SALARY_COMPONENTS_LOADING";
export const UPDATE_SALARY_COMPONENTS_SUCCESS =
  "UPDATE_SALARY_COMPONENTS_SUCCESS";
export const UPDATE_SALARY_COMPONENTS_ERROR = "UPDATE_SALARY_COMPONENTS_ERROR";

// NotificationsContext action types
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";
export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS";

// TeamsContext action types
export const CREATE_TEAM = "CREATE_TEAM";
export const CREATE_TEAM_LOADING = "CREATE_TEAM_LOADING";
export const CREATE_TEAM_SUCCESS = "CREATE_TEAM_SUCCESS";
export const CREATE_TEAM_ERROR = "CREATE_TEAM_ERROR";

export const ADD_TEAM_MEMBER = "ADD_TEAM_MEMBER";
export const ADD_TEAM_MEMBER_LOADING = "ADD_TEAM_MEMBER_LOADING";
export const ADD_TEAM_MEMBER_SUCCESS = "ADD_TEAM_MEMBER_SUCCESS";
export const ADD_TEAM_MEMBER_ERROR = "ADD_TEAM_MEMBER_ERROR";

export const REMOVE_TEAM_MEMBER = "REMOVE_TEAM_MEMBER";
export const REMOVE_TEAM_MEMBER_LOADING = "REMOVE_TEAM_MEMBER_LOADING";
export const REMOVE_TEAM_MEMBER_SUCCESS = "REMOVE_TEAM_MEMBER_SUCCESS";
export const REMOVE_TEAM_MEMBER_ERROR = "REMOVE_TEAM_MEMBER_ERROR";

export const UPDATE_TEAM_INFO = "UPDATE_TEAM_INFO";
export const UPDATE_TEAM_INFO_LOADING = "UPDATE_TEAM_INFO_LOADING";
export const UPDATE_TEAM_INFO_SUCCESS = "UPDATE_TEAM_INFO_SUCCESS";
export const UPDATE_TEAM_INFO_ERROR = "UPDATE_TEAM_INFO_ERROR";

// ProjectsContext action types
export const CREATE_PROJECT = "CREATE_PROJECT";
export const CREATE_PROJECT_LOADING = "CREATE_PROJECT_LOADING";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_ERROR = "CREATE_PROJECT_ERROR";

export const ADD_PROJECT_MEMBER = "ADD_PROJECT_MEMBER";
export const ADD_PROJECT_MEMBER_LOADING = "ADD_PROJECT_MEMBER_LOADING";
export const ADD_PROJECT_MEMBER_SUCCESS = "ADD_PROJECT_MEMBER_SUCCESS";
export const ADD_PROJECT_MEMBER_ERROR = "ADD_PROJECT_MEMBER_ERROR";

export const REMOVE_PROJECT_MEMBER = "REMOVE_PROJECT_MEMBER";
export const REMOVE_PROJECT_MEMBER_LOADING = "REMOVE_PROJECT_MEMBER_LOADING";
export const REMOVE_PROJECT_MEMBER_SUCCESS = "REMOVE_PROJECT_MEMBER_SUCCESS";
export const REMOVE_PROJECT_MEMBER_ERROR = "REMOVE_PROJECT_MEMBER_ERROR";

export const UPDATE_PROJECT_INFO = "UPDATE_PROJECT_INFO";
export const UPDATE_PROJECT_INFO_LOADING = "UPDATE_PROJECT_INFO_LOADING";
export const UPDATE_PROJECT_INFO_SUCCESS = "UPDATE_PROJECT_INFO_SUCCESS";
export const UPDATE_PROJECT_INFO_ERROR = "UPDATE_PROJECT_INFO_ERROR";

// TasksContext action types
export const CREATE_TASK = "CREATE_TASK";
export const CREATE_TASK_LOADING = "CREATE_TASK_LOADING";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_ERROR = "CREATE_TASK_ERROR";

export const ASSIGN_TASK = "ASSIGN_TASK";
export const ASSIGN_TASK_LOADING = "ASSIGN_TASK_LOADING";
export const ASSIGN_TASK_SUCCESS = "ASSIGN_TASK_SUCCESS";
export const ASSIGN_TASK_ERROR = "ASSIGN_TASK_ERROR";

export const COMPLETE_TASK = "COMPLETE_TASK";
export const COMPLETE_TASK_LOADING = "COMPLETE_TASK_LOADING";
export const COMPLETE_TASK_SUCCESS = "COMPLETE_TASK_SUCCESS";
export const COMPLETE_TASK_ERROR = "COMPLETE_TASK_ERROR";

export const UPDATE_TASK = "UPDATE_TASK";
export const UPDATE_TASK_LOADING = "UPDATE_TASK_LOADING";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_ERROR = "UPDATE_TASK_ERROR";

// AdminContext action types
export const UPDATE_USER_PERMISSIONS = "UPDATE_USER_PERMISSIONS";
export const UPDATE_USER_PERMISSIONS_LOADING =
  "UPDATE_USER_PERMISSIONS_LOADING";
export const UPDATE_USER_PERMISSIONS_SUCCESS =
  "UPDATE_USER_PERMISSIONS_SUCCESS";
export const UPDATE_USER_PERMISSIONS_ERROR = "UPDATE_USER_PERMISSIONS_ERROR";


// {/** */}
// BackupContext action types
export const SCHEDULE_BACKUP = "SCHEDULE_BACKUP";
export const SCHEDULE_BACKUP_LOADING = "SCHEDULE_BACKUP_LOADING";
export const SCHEDULE_BACKUP_SUCCESS = "SCHEDULE_BACKUP_SUCCESS";
export const SCHEDULE_BACKUP_ERROR = "SCHEDULE_BACKUP_ERROR";

export const GET_BACKUP_STATUS = "GET_BACKUP_STATUS";
export const GET_BACKUP_STATUS_LOADING = "GET_BACKUP_STATUS_LOADING";
export const GET_BACKUP_STATUS_SUCCESS = "GET_BACKUP_STATUS_SUCCESS";
export const GET_BACKUP_STATUS_ERROR = "GET_BACKUP_STATUS_ERROR";

// DataDownloadContext action types
export const DOWNLOAD_DATA = "DOWNLOAD_DATA";
export const DOWNLOAD_DATA_LOADING = "DOWNLOAD_DATA_LOADING";
export const DOWNLOAD_DATA_SUCCESS = "DOWNLOAD_DATA_SUCCESS";
export const DOWNLOAD_DATA_ERROR = "DOWNLOAD_DATA_ERROR";

// MessagingContext action types
export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_MESSAGE_LOADING = "SEND_MESSAGE_LOADING";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_ERROR = "SEND_MESSAGE_ERROR";

// AnnouncementsContext action types
export const CREATE_ANNOUNCEMENT = "CREATE_ANNOUNCEMENT";
export const CREATE_ANNOUNCEMENT_LOADING = "CREATE_ANNOUNCEMENT_LOADING";
export const CREATE_ANNOUNCEMENT_SUCCESS = "CREATE_ANNOUNCEMENT_SUCCESS";
export const CREATE_ANNOUNCEMENT_ERROR = "CREATE_ANNOUNCEMENT_ERROR";

export const DELETE_ANNOUNCEMENT = "DELETE_ANNOUNCEMENT";
export const DELETE_ANNOUNCEMENT_LOADING = "DELETE_ANNOUNCEMENT_LOADING";
export const DELETE_ANNOUNCEMENT_SUCCESS = "DELETE_ANNOUNCEMENT_SUCCESS";
export const DELETE_ANNOUNCEMENT_ERROR = "DELETE_ANNOUNCEMENT_ERROR";

export const UPDATE_ANNOUNCEMENT = "UPDATE_ANNOUNCEMENT";
export const UPDATE_ANNOUNCEMENT_LOADING = "UPDATE_ANNOUNCEMENT_LOADING";
export const UPDATE_ANNOUNCEMENT_SUCCESS = "UPDATE_ANNOUNCEMENT_SUCCESS";
export const UPDATE_ANNOUNCEMENT_ERROR = "UPDATE_ANNOUNCEMENT_ERROR";

// CheckInContext action types
export const CHECK_IN_EMPLOYEE = "CHECK_IN_EMPLOYEE";
export const CHECK_IN_EMPLOYEE_LOADING = "CHECK_IN_EMPLOYEE_LOADING";
export const CHECK_IN_EMPLOYEE_SUCCESS = "CHECK_IN_EMPLOYEE_SUCCESS";
export const CHECK_IN_EMPLOYEE_ERROR = "CHECK_IN_EMPLOYEE_ERROR";
