// SubscriptionContext action types
export const SUBSCRIBE_PLAN = "SUBSCRIBE_PLAN";
export const SUBSCRIBE_PLAN_LOADING = "SUBSCRIBE_PLAN_LOADING";
export const SUBSCRIBE_PLAN_SUCCESS = "SUBSCRIBE_PLAN_SUCCESS";
export const SUBSCRIBE_PLAN_ERROR = "SUBSCRIBE_PLAN_ERROR";

export const CANCEL_SUBSCRIPTION = "CANCEL_SUBSCRIPTION";
export const CANCEL_SUBSCRIPTION_LOADING = "CANCEL_SUBSCRIPTION_LOADING";
export const CANCEL_SUBSCRIPTION_SUCCESS = "CANCEL_SUBSCRIPTION_SUCCESS";
export const CANCEL_SUBSCRIPTION_ERROR = "CANCEL_SUBSCRIPTION_ERROR";

export const UPDATE_PAYMENT_METHOD = "UPDATE_PAYMENT_METHOD";
export const UPDATE_PAYMENT_METHOD_LOADING = "UPDATE_PAYMENT_METHOD_LOADING";
export const UPDATE_PAYMENT_METHOD_SUCCESS = "UPDATE_PAYMENT_METHOD_SUCCESS";
export const UPDATE_PAYMENT_METHOD_ERROR = "UPDATE_PAYMENT_METHOD_ERROR";

export const GET_INVOICE = "GET_INVOICE";
export const GET_INVOICE_LOADING = "GET_INVOICE_LOADING";
export const GET_INVOICE_SUCCESS = "GET_INVOICE_SUCCESS";
export const GET_INVOICE_ERROR = "GET_INVOICE_ERROR";

// BillingContext action types
export const PROCESS_PAYMENT = "PROCESS_PAYMENT";
export const PROCESS_PAYMENT_LOADING = "PROCESS_PAYMENT_LOADING";
export const PROCESS_PAYMENT_SUCCESS = "PROCESS_PAYMENT_SUCCESS";
export const PROCESS_PAYMENT_ERROR = "PROCESS_PAYMENT_ERROR";

// OrganizationSetupContext action types
export const CREATE_ORGANIZATION = "CREATE_ORGANIZATION";
export const CREATE_ORGANIZATION_LOADING = "CREATE_ORGANIZATION_LOADING";
export const CREATE_ORGANIZATION_SUCCESS = "CREATE_ORGANIZATION_SUCCESS";
export const CREATE_ORGANIZATION_ERROR = "CREATE_ORGANIZATION_ERROR";

export const UPDATE_ORGANIZATION_DETAILS = "UPDATE_ORGANIZATION_DETAILS";
export const UPDATE_ORGANIZATION_DETAILS_LOADING =
  "UPDATE_ORGANIZATION_DETAILS_LOADING";
export const UPDATE_ORGANIZATION_DETAILS_SUCCESS =
  "UPDATE_ORGANIZATION_DETAILS_SUCCESS";
export const UPDATE_ORGANIZATION_DETAILS_ERROR =
  "UPDATE_ORGANIZATION_DETAILS_ERROR";

export const SET_UP_HR_PLATFORM = "SET_UP_HR_PLATFORM";
export const SET_UP_HR_PLATFORM_LOADING = "SET_UP_HR_PLATFORM_LOADING";
export const SET_UP_HR_PLATFORM_SUCCESS = "SET_UP_HR_PLATFORM_SUCCESS";
export const SET_UP_HR_PLATFORM_ERROR = "SET_UP_HR_PLATFORM_ERROR";

// Add more action types as needed for other billing and setup-related processes
